version: '3'
services:
  db1:
    image: mysql:8
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=12345"
        #ports:
      #-:3306"
  web:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile'
      args:
        JAR_FILE: "build/libs/todo-0.0.1-SNAPSHOT.jar"
    restart: always
    ports:
      - "3000:3000"
    # volumes:
    #  - ./cbapi-footballpools:/app
    depends_on:
      - db1
      #- redis
