version: '3.7'

services:
  app:
    image: jdk8-app:0.0.1
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mysql:8.0.14
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_PASSWORD=spring
      - MYSQL_USER=spring
      - MYSQL_DATABASE=todos_db
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password
