logging:
  level:
    org.springframework: ERROR
    com.app.todo: DEBUG

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://database:3306/todos_db
    username: spring
    password: spring
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: facebook-client-id
            clientSecret: facebook-client-secret
          google:
            clientId: google-client-id
            clientSecret: google-client-secret
  messages:
    basename: validation
